### ISSUE TITLE
Debugging in/out

### ISSUE THREAD

**Issue by ShaneMcC** [ShaneMcC/DFBnc#101]
Add debugging for IRC Messages in/out to aid in debugging strangeness.

**Comment by ShaneMcC** [comment]
Maybe want to make it only available to the local client to prevent bouncer admins from doing bad things (on shared bouncers) although this could easily be circumvented by just recompiling the bouncer.

Still probably want to do it though to prevent accidental viewing of other users traffic. (Although shared bouncers seem icky!)

**Comment by csmith** [comment]
Local client makes sense. Would be fairly annoying to sift through stuff from other {servers,users} when debugging.

**Comment by ShaneMcC** [comment]
Enable with: /raw dfbnc debug flag .*(in|out)
Disable with: /raw dfbnc debug unflag .*(in|out)

This will cause the IRC in/out messages to be sent by PRIVMSG from -BNC_DEBUG

WARNING: These messages may end up being longer than 512 which may upset some clients.
