### ISSUE TITLE
Switch to using IRCv3 server-time extension

### ISSUE THREAD

**Issue by csmith** [ShaneMcC/DFBnc#102]
http://ircv3.net/specs/extensions/server-time-3.2.html

Instead of the custom capability currently used.

**Comment by ShaneMcC** [comment]
Already supported :)

https://github.com/ShaneMcC/DFBnc/blob/master/src/com/dfbnc/sockets/UserSocket.java#L173
and
https://github.com/ShaneMcC/DFBnc/blob/master/src/com/dfbnc/servers/irc/IRCConnectionHandler.java#L1642

It even takes priority over our custom one if both are requested :)

DMDirc/Parser doesn't yet do message-tags though so still uses the old one.
