### ISSUE TITLE
readonly clients should be non admin clients

### ISSUE THREAD

**Issue by greboid** [ShaneMcC/DFBnc#112]
As well as not being able to write the config, all readonly clients should be non admin users.  I cant think of a use case you'd want to be readonly AND admin.

**Comment by ShaneMcC** [comment]
This is annoying :(

Admin is a property of the account along with the CommandManager.

ReadOnly is a property of the UserSocket.

**Comment by ShaneMcC** [comment]
Less annoying than I thought!
