### ISSUE TITLE
SSL connections don't work.

### ISSUE THREAD

**Issue by csmith** [ShaneMcC/DFBnc#63]
With a clean build running on OpenJDK 8, it seems like you can only connect to an SSL socket once, then all future connections fail.

DMDirc shows a mixture of broken pipes and unsupported protocol errors, which suggests that either DFBnc is killing the connection too early, or it's sending something it shouldn't...

**Comment by ShaneMcC** [comment]
This was introduced in b2973a5e6cf43b77c01ec2e2b4fcdd27c66bbcd2 and should be fixed now by adac0d68cd790f5ffb3980f647372ea834ea4882
