### ISSUE TITLE
Bot commands from commands containing printf sequences fail

### ISSUE THREAD

**Issue by csmith** [ShaneMcC/DFBnc#82]
If a bot command contains something like %s (or just % on its own), it never reaches the user.

This is because CommandOutput runs the message and arguments through String.format, and then passes them on to UserSocket which does the same again.

Quick and dirty way to reproduce:

    dfbnc debug raw ping %s

(generates no response to the user)

**Comment by ShaneMcC** [comment]
Most instances of passing strings to the COB have now been converted to always pass user input in via a formatted string (619a1392529d5a30a2dfec5dfca9893522cec196 and 571d75bb845566836ae79104efb0033b9fa41803) and my previous commit will catch any unformatted strings and prevent them passing through the formatter unless it is expected.
