### ISSUE TITLE
Add "offlinecount" setting

### ISSUE THREAD

**Issue by ShaneMcC** [ShaneMcC/DFBnc#93]
lastDetach/partondetach/offlineawayreason etc don't play nice with "always connected" clients (eg a local running irssi or tapchat).

Some people may want these clients not to count for the purposes of certain "offline" features, so implement an "offlinecount" setting.

If we drop below "offlinecount" connected clients, assume offline for the purposes of performing lastDetach and offline actions.

**Comment by greboid** [comment]
Counts are awful and really likely to go wrong.  You have subclients with config settings, just add a setting for subclient to be excluded from being counted as online.

**Comment by ShaneMcC** [comment]
This is a duplicate of #38 it seems!

I'll close #38 as I think this explains the need better (more than just dperform)
